import strformat, stint

type
  Item* = object
    chainId: int
    contractAddress: string
    tokenId: UInt256
    name: string
    mediaUrl: string
    mediaType: string
    imageUrl: string
    backgroundColor: string
    collectionName: string
    collectionSlug: string
    collectionImageUrl: string
    isLoading: bool
    isPinned: bool
    communityId: string
    communityName: string
    communityColor: string
    communityPrivilegesLevel: int

proc initItem*(
  chainId: int,
  contractAddress: string,
  tokenId: UInt256,
  name: string,
  mediaUrl: string,
  mediaType: string,
  imageUrl: string,
  backgroundColor: string,
  collectionName: string,
  collectionSlug: string,
  collectionImageUrl: string,
  isPinned: bool,
  communityId: string,
  communityName: string,
  communityColor: string,
  communityPrivilegesLevel: int

): Item =
  result.chainId = chainId
  result.contractAddress = contractAddress
  result.tokenId = tokenId
  result.name = if (name != ""): name else: ("#" & tokenId.toString())
  result.mediaUrl = mediaUrl
  result.mediaType = mediaType
  result.imageUrl = imageUrl
  result.backgroundColor = if (backgroundColor == ""): "transparent" else: ("#" & backgroundColor)
  result.collectionName = collectionName
  result.collectionSlug = collectionSlug
  result.collectionImageUrl = collectionImageUrl
  result.isLoading = false
  result.isPinned = isPinned
  result.communityId = communityId
  result.communityName = communityName
  result.communityColor = communityColor
  result.communityPrivilegesLevel = communityPrivilegesLevel

proc initItem*: Item =
  result = initItem(0, "", u256(0), "", "", "", "", "transparent", "Collectibles", "", "", false, "", "", "", 0)

proc initLoadingItem*: Item =
  result = initItem()
  result.isLoading = true

proc `$`*(self: Item): string =
  result = fmt"""Collectibles(
    chainId: {self.chainId},
    contractAddress: {self.contractAddress},
    tokenId: {self.tokenId},
    name: {self.name},
    mediaUrl: {self.mediaUrl},
    mediaType: {self.mediaType},
    imageUrl: {self.imageUrl},
    backgroundColor: {self.backgroundColor},
    collectionName: {self.collectionName},
    collectionSlug: {self.collectionSlug},
    collectionImageUrl: {self.collectionImageUrl},
    isLoading: {self.isLoading},
    isPinned: {self.isPinned},
    communityId: {self.communityId},
    communityName: {self.communityName},
    communityColor: {self.communityColor},
    communityPrivilegesLevel: {self.communityPrivilegesLevel},
    ]"""

proc getChainId*(self: Item): int =
  return self.chainId

proc getContractAddress*(self: Item): string =
  return self.contractAddress

proc getTokenId*(self: Item): UInt256 =
  return self.tokenId

# Unique ID to identify collectible, generated by us
proc getId*(self: Item): string =
  return fmt"{self.getChainId}+{self.getContractAddress}+{self.getTokenID}"

proc getName*(self: Item): string =
  return self.name

proc getMediaUrl*(self: Item): string =
  return self.mediaUrl

proc getMediaType*(self: Item): string =
  return self.mediaType

proc getImageUrl*(self: Item): string =
  return self.imageUrl

proc getBackgroundColor*(self: Item): string =
  return self.backgroundColor

# Unique ID to identify collection, generated by us
proc getCollectionId*(self: Item): string =
  return fmt"{self.getChainId}+{self.getContractAddress}"

proc getCollectionName*(self: Item): string =
  return self.collectionName

proc getCollectionSlug*(self: Item): string =
  return self.collectionSlug

proc getCollectionImageUrl*(self: Item): string =
  return self.collectionImageUrl

proc getIsLoading*(self: Item): bool =
  return self.isLoading

proc getIsPinned*(self: Item): bool =
  return self.isPinned

proc getCommunityId*(self: Item): string =
  return self.communityId

proc getCommunityName*(self: Item): string =
  return self.communityName

proc getCommunityColor*(self: Item): string =
  return self.communityColor

proc getCommunityPrivilegesLevel*(self: Item): int =
  return self.communityPrivilegesLevel
