#!/bin/bash
APPDIR="$(dirname "$(readlink -f "${0}")")"
export GST_PLUGIN_SCANNER="${APPDIR}/usr/lib/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
export GST_PLUGIN_PATH="${APPDIR}/usr/lib/gstreamer-1.0"
export GST_PLUGIN_PATH_1_0="${APPDIR}/usr/lib/gstreamer-1.0"
export GST_PLUGIN_SYSTEM_PATH="${APPDIR}/usr/lib/gstreamer-1.0"
export GST_PLUGIN_SYSTEM_PATH_1_0="${APPDIR}/usr/lib/gstreamer-1.0"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/:${APPDIR}/usr/lib/nss:${LD_LIBRARY_PATH}"
export QT_QPA_PLATFORM="xcb"
# TODO: Remove once qt 5.15.2 support is dropped
# Fixing bug: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
export QTWEBENGINE_CHROMIUM_FLAGS="${QTWEBENGINE_CHROMIUM_FLAGS} --disable-seccomp-filter-sandbox"

# Set up pcsc-lite environment
export PCSC_DRIVERS_DIR="${APPDIR}/usr/lib/pcsc/drivers"
export PCSCLITE_CONFIG_DIR="${APPDIR}/etc/reader.conf.d"

# Start pcscd
# warning: needs to be same as ipcdir in ci/Dockerfile
# https://salsa.debian.org/rousseau/PCSC/-/blob/master/meson.options?ref_type=heads#L36
PCSCD_RUN_DIR="/tmp/pcscd/run"
rm -rf "${PCSCD_RUN_DIR}"
mkdir -p "${PCSCD_RUN_DIR}"
echo "starting pcscd with ${APPDIR}/usr/bin/pcscd -f &"
"${APPDIR}/usr/bin/pcscd" -f &

DEFAULT_LANG=en_US.UTF-8
if [[ "$LANG" == "C.UTF-8" ]]
then
  export LANG=$DEFAULT_LANG
else
  export LANG="${VARIABLE:=$DEFAULT_LANG}"
fi

exec "${APPDIR}/usr/bin/nim_status_client" "$@"
