#!/bin/bash
APPDIR="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/:${LD_LIBRARY_PATH}"
export QT_QPA_PLATFORM="xcb"

DEFAULT_LANG=en_US.UTF-8
if [[ "$LANG" == "C.UTF-8" ]]
then
  export LANG=$DEFAULT_LANG
else
  export LANG="${VARIABLE:=$DEFAULT_LANG}"
fi

exec "${APPDIR}/usr/bin/nim_status_client" "$@"
