const SEARCH_MENU_LOCATION_CHAT_SECTION_NAME* = "Chat"

const SEARCH_RESULT_COMMUNITIES_SECTION_NAME* = "Communities"
const SEARCH_RESULT_CHATS_SECTION_NAME* = "Chats"
const SEARCH_RESULT_CHANNELS_SECTION_NAME* = "Channels"
const SEARCH_RESULT_MESSAGES_SECTION_NAME* = "Messages"
