from enum import Enum


class Keycard(Enum):
    KEYCARD_PIN = '000000'
    KEYCARD_NAME = 'Test Keycard'
    ACCOUNT_NAME = 'Test Account'
    KEYCARD_POPUP_HEADER_CREATE_SEED = 'Create a new Keycard account with a new seed phrase'
    KEYCARD_POPUP_HEADER_IMPORT_SEED = 'Import or restore a Keycard via a seed phrase'
    KEYCARD_POPUP_HEADER_SET_UP_EXISTING = 'Set up a new Keycard with an existing account'
    KEYCARD_INSTRUCTIONS_PLUG_IN = 'Plug in Keycard reader...'
    KEYCARD_INSTRUCTIONS_INSERT_KEYCARD = 'Insert Keycard...'
    KEYCARD_RECOGNIZED = 'Keycard recognized'
    KEYCARD_CHOOSE_PIN = 'Choose a Keycard PIN'
    KEYCARD_PIN_NOTE = 'It is very important that you do not lose this PIN'
    KEYCARD_REPEAT_PIN = 'Repeat Keycard PIN'
    KEYCARD_PIN_SET = 'Keycard PIN set'
    KEYCARD_NAME_KEYCARD = 'Name this Keycard'
    KEYCARD_NAME_ACCOUNTS = 'Name accounts'
    KEYCARD_NEW_ACCOUNT_CREATED = 'New account successfully created'
    KEYCARD_READY = 'Keycard is ready to use!'
    KEYCARD_SELECT_KEYPAIR = 'Select a key pair'
    KEYCARD_SELECT_WHICH_PAIR = 'Select which key pair you’d like to move to this Keycard'
    KEYCARD_KEYPAIR_INFO = 'Moving this key pair will require you to use your Keycard to login'
    KEYCARD_MIGRATING = 'Migrating key pair to Keycard'
    KEYCARD_KEYPAIR_MIGRATED = 'Keypair successfully migrated'
    KEYCARD_COMPLETE_MIGRATION = 'To complete migration close Status and log in with your new Keycard'
