import strformat, stint
import backend/activity as backend

type
  CollectibleItem* = object
    chainId: int
    contractAddress: string
    tokenId: UInt256
    name: string
    imageUrl: string

proc initItem*(
  chainId: int,
  contractAddress: string,
  tokenId: UInt256,
  name: string,
  imageUrl: string
): CollectibleItem =
  result.chainId = chainId
  result.contractAddress = contractAddress
  result.tokenId = tokenId
  result.name = if (name != ""): name else: ("#" & tokenId.toString())
  result.imageUrl = imageUrl

proc collectibleToItem*(c: backend.CollectibleHeader) : CollectibleItem =
  return initItem(
    c.id.contractID.chainID,
    c.id.contractID.address,
    c.id.tokenID,
    c.name,
    c.imageUrl
  )

proc `$`*(self: CollectibleItem): string =
  result = fmt"""Collectibles(
    chainId: {self.chainId},
    contractAddress: {self.contractAddress},
    tokenId: {self.tokenId},
    name: {self.name},
    imageUrl: {self.imageUrl}
    ]"""

proc getChainId*(self: CollectibleItem): int =
  return self.chainId

proc getContractAddress*(self: CollectibleItem): string =
  return self.contractAddress

proc getTokenId*(self: CollectibleItem): UInt256 =
  return self.tokenId

# Unique ID to identify collectible, generated by us
proc getId*(self: CollectibleItem): string =
  return fmt"{self.getChainId}+{self.getContractAddress}+{self.getTokenID}"

proc getName*(self: CollectibleItem): string =
  return self.name

proc getImageUrl*(self: CollectibleItem): string =
  return self.imageUrl

