name: 'Qt Android Architecture Mapping'
description: 'Maps input architecture to Qt Android folder naming convention'

inputs:
  architecture:
    description: 'Target architecture (arm64, arm, x86_64, x86)'
    required: true
  qt-version:
    description: 'Qt version'
    required: true

outputs:
  qt-android-path:
    description: 'Full Qt Android path'
    value: /opt/qt/${{ inputs.qt-version }}/android_${{ inputs.architecture == 'arm64' && 'arm64_v8a' || inputs.architecture == 'arm' && 'armv7' || inputs.architecture }}
  qt-host-path:
    description: 'Qt host tools path'
    value: /opt/qt/${{ inputs.qt-version }}/gcc_64

runs:
  using: "composite"
  steps:
    - run: echo "Mapping architecture ${{ inputs.architecture }} for Qt ${{ inputs.qt-version }}"
      shell: bash 