name: Android Build APK

on:
  workflow_dispatch

jobs:
  android-build:
    runs-on: ubuntu-latest
    name: Build Android APK
    container:
      image: carlonluca/qt-dev:6.8.3

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_HOME: /opt/android-sdk
      ANDROID_NDK_HOME: /opt/android-sdk/ndk/26.1.10909125
      SDK_PATH: /opt/android-sdk
      ARCH: arm64
      QT_PATH: /opt/qt/6.8.3
      QT_HOST_PATH: /opt/qt/6.8.3/gcc_64
      QT_ANDROID_PATH: /opt/qt/6.8.3/android_arm64_v8a
      PATH: /opt/qt/6.8.3/android_arm64_v8a/bin:/opt/qt/6.8.3/gcc_64/bin:/opt/qt/6.8.3/gcc_64/libexec:/opt/qt/6.8.3/android_arm64_v8a/libexec:/opt/android-sdk/emulator:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/android-sdk/platform-tools:/usr/bin:/bin:/usr/local/bin
      PKG_CONFIG_PATH: /opt/qt/6.8.3/android_arm64_v8a/lib/pkgconfig
      ANDROID_ABI: arm64-v8a
      USE_SYSTEM_NIM: 1

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -yq curl

          curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
          $HOME/.nimble/bin/choosenim 2.0.12
          echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: go.sum

      - name: Install Go tools
        run: |
          go install github.com/go-bindata/go-bindata/v3/go-bindata@latest
          go install go.uber.org/mock/mockgen@v0.4.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1

      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Android APK
        run: |
          make V=3

