import QtQuick

import utils

import Models

ListModel {
    Component.onCompleted:
        append([{
                    id: "0x0001",
                    name: "I am 0wner!1!!",
                    description: ModelsData.descriptions.shortLoremIpsum,
                    introMessage: "Welcome to ze club",
                    outroMessage: "Sad to see you go",
                    joined: true,
                    spectated: false,
                    memberRole: Constants.memberRole.owner,
                    isControlNode: true,
                    image: ModelsData.icons.dribble,
                    color: "yellow",
                    muted: false,
                    members: [ { pubKey: "0xdeadbeef" } ],
                    membersCount: 1,
                    activeMembersCount: 1,
                    loading: false,
                    permissionsModel: [],
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0002",
                    name: "Test community 2",
                    description: ModelsData.descriptions.longLoremIpsum,
                    introMessage: "Welcome to ze club",
                    outroMessage: "Sad to see you go",
                    joined: true,
                    spectated: false,
                    memberRole: Constants.memberRole.none,
                    isControlNode: false,
                    image: ModelsData.icons.status,
                    color: "peach",
                    muted: false,
                    members: [ { pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" } ],
                    membersCount: 3,
                    activeMembersCount: 3,
                    loading: false,
                    permissionsModel: [],
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0003",
                    name: "Free to join",
                    introMessage: "Welcome to ze club",
                    description: ModelsData.descriptions.longLoremIpsum,
                    outroMessage: "Sad to see you go",
                    joined: false,
                    spectated: true,
                    memberRole: Constants.memberRole.none,
                    isControlNode: false,
                    image: ModelsData.icons.dragonereum,
                    color: "red",
                    muted: false,
                    members: [ { pubKey: "0xdeadbeef" } ],
                    membersCount: 1,
                    activeMembersCount: 1,
                    loading: false,
                    permissionsModel: PermissionsModel.moreThanTwoInitialShortPermissionsModel,
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0004",
                    name: "Muted community",
                    introMessage: "Welcome to ze club",
                    description: ModelsData.descriptions.shortLoremIpsum,
                    outroMessage: "Sad to see you go",
                    joined: true,
                    spectated: false,
                    memberRole: Constants.memberRole.none,
                    isControlNode: false,
                    image: ModelsData.icons.coinbase,
                    color: "whitesmoke",
                    muted: true,
                    members: [],
                    membersCount: 0,
                    activeMembersCount: 0,
                    loading: false,
                    permissionsModel: [],
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0005",
                    name: "Admin test community",
                    description: ModelsData.descriptions.shortLoremIpsum,
                    introMessage: "Welcome to ze club",
                    outroMessage: "Sad to see you go",
                    joined: true,
                    spectated: false,
                    memberRole: Constants.memberRole.admin,
                    isControlNode: false,
                    image: ModelsData.icons.socks,
                    color: "green",
                    muted: false,
                    members: [{ pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" }],
                    membersCount: 4,
                    activeMembersCount: 4,
                    loading: false,
                    permissionsModel: [],
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0006",
                    name: "Pending request here",
                    description: ModelsData.descriptions.shortLoremIpsum,
                    introMessage: "Welcome to ze club",
                    outroMessage: "Sad to see you go",
                    joined: false,
                    spectated: true,
                    memberRole: Constants.memberRole.none,
                    isControlNode: false,
                    image: ModelsData.icons.spotify,
                    color: "pink",
                    muted: false,
                    members: [{ pubKey: "0xdeadbeef" }],
                    membersCount: 1,
                    activeMembersCount: 1,
                    loading: false,
                    permissionsModel: PermissionsModel.privatePermissionsMemberNotMetModel,
                    allTokenRequirementsMet: false
                },
                {
                    id: "0x0007",
                    name: "Token Master Club",
                    description: ModelsData.descriptions.mediumLoremIpsum,
                    introMessage: "Welcome to ze club",
                    outroMessage: "Sad to see you go",
                    joined: true,
                    spectated: false,
                    memberRole: Constants.memberRole.tokenMaster,
                    image: ModelsData.icons.cryptPunks,
                    color: "lightslategrey",
                    muted: false,
                    members: [{ pubKey: "0xdeadbeef" }, { pubKey: "0xdeadbeef" }],
                    membersCount: 2,
                    activeMembersCount: 2,
                    loading: false,
                    permissionsModel: [],
                    allTokenRequirementsMet: false
                }
               ])
}
