import QtQuick 2.15

import utils 1.0

ListModel {
    Component.onCompleted: append([
    {
        id: "id1",
        sectionType: Constants.appSection.chat,
        icon: "chat",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Messages",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 442
    },
    {
        id: "id2",
        sectionType: Constants.appSection.wallet,
        icon: "wallet",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Wallet",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0
    },
    {
        id: "id3",
        sectionType: Constants.appSection.profile,
        icon: "settings",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Settings",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0
    },
    {
        id: "id4",
        sectionType: Constants.appSection.node,
        icon: "node",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Node",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: false,
        hasNotification: false,
        notificationsCount: 0
    },
    {
        id: "id5",
        sectionType: Constants.appSection.communitiesPortal,
        icon: "communities",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Communities",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 42
    },
    {
        id: "id6",
        sectionType: Constants.appSection.loadingSection,
        icon: "loading",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0
    },
    {
        id: "id7",
        sectionType: Constants.appSection.swap,
        icon: "swap",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Swap",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0
    },
    {
        id: "id8",
        sectionType: Constants.appSection.market,
        icon: "market",
        image: "",
        bannerImageData: "",
        color: "mediumblue",
        name: "Market",
        description: "",
        allMembers: [],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0
    },
    {
        id: "id9",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.status,
        bannerImageData: ModelsData.banners.status,
        color: "mediumblue",
        name: "Status.app",
        description: "",
        allMembers: [],
        activeMembersCount: 61,
        enabled: true,
        hasNotification: true,
        notificationsCount: 3
    },
    {
        id: "id10",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.superRare,
        bannerImageData: ModelsData.banners.superRare,
        color: "slategray",
        name: "SuperRare",
        description: "",
        allMembers: [],
        activeMembersCount: 4,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0
    },
    {
        id: "id11",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.coinbase,
        bannerImageData: ModelsData.banners.coinbase,
        color: "olive",
        name: "Coinbase",
        description: "",
        allMembers: [],
        activeMembersCount: 20,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0,
        spectated: true,
        joined: false
    },
    {
        id: "id12",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.socks,
        bannerImageData: ModelsData.banners.socks,
        color: "yellow",
        name: "Socks",
        description: "",
        allMembers: [],
        activeMembersCount: 20,
        enabled: true,
        hasNotification: false,
        notificationsCount: 33
    },
    {
        id: "id13",
        sectionType: Constants.appSection.community,
        icon: "",
        image:  ModelsData.icons.rarible,
        bannerImageData: "",
        color: "pink",
        name: "Rarible",
        description: "",
        allMembers: [],
        activeMembersCount: 1,
        enabled: true,
        hasNotification: false,
        notificationsCount: 33,
        amIBanned: true
    },
    {
        id: "id14",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.spotify,
        bannerImageData: "",
        color: "green",
        name: "Spotify",
        description: "",
        allMembers: ["foo"],
        activeMembersCount: 200,
        enabled: true,
        hasNotification: true,
        notificationsCount: 0
    },
    {
        id: "id15",
        sectionType: Constants.appSection.community,
        icon: "",
        image: ModelsData.icons.dribble,
        bannerImageData: "",
        color: "orange",
        name: "Dribble",
        description: "",
        allMembers: ["foo", "bar", "baz"],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: true,
        notificationsCount: 100
    },
    {
        id: "id16",
        sectionType: Constants.appSection.community,
        icon: "",
        image: "",
        bannerImageData: "",
        color: "crimson",
        name: "Just Text",
        description: "",
        allMembers: ["foo"],
        activeMembersCount: 0,
        enabled: true,
        hasNotification: false,
        notificationsCount: 0
    },
    ])
}
