name: Lint
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Check `nph` formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # In PR, has extra merge commit: ^1 = PR, ^2 = base

      - name: Check nph formatting
        # Pin nph to a specific version to avoid sudden style differences.
        # Updating nph version should be accompanied with running the new
        # version on the fluffy directory.
        run: |
          VERSION="v0.6.0"
          ARCHIVE="nph-linux_x64.tar.gz"
          curl -L "https://github.com/arnetheduck/nph/releases/download/${VERSION}/${ARCHIVE}" -o ${ARCHIVE}
          tar -xzf ${ARCHIVE}
          ./nph src test
          git diff --exit-code
